#! /usr/bin/env python3

import os, re, datetime, subprocess

sys_dir = os.path.abspath(os.path.join(os.path.dirname(__file__), os.pardir))
ver_file = os.path.join(sys_dir, 'app', 'server', 'sd_version.py')

with open(ver_file) as f:
    line = f.readline()
    
line = re.sub(r'[\d]{6}', datetime.date.today().strftime('%y%m%d'), line)

with open(ver_file, 'w') as f:
    f.write(line)

subprocess.call(f'git add {ver_file}', shell=True)
