
services:
  jupyter:
    image: slowproj/slowpy-notebook
    command:
      - start-notebook.sh
      - --NotebookApp.base_url=/jupyter
      - --NotebookApp.token=''
      - --NotebookApp.password=''
    expose:
      - "8888"
    volumes:
      - ./notebooks:/home/jovyan
    environment:
      JUPYTER_BASE_URL: "/jupyter"


  slowdash:
    image: slowproj/slowdash
    volumes:
      - .:/project
    expose:
      - "18881"
    environment:
      - JUPYTER_URL=https://localhost/jupyter
      - JUPYTER_TOKEN=""
      - JUPYTER_INTERNAL_URL=http://jupyter:8888/jupyter
      - SLOWDASH_INTERNAL_URL=http://slowdash:18881
      

  nginx:
    build: ./nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - slowdash
      - jupyter
