#### Example for dynamically adding a channel for time-range-dependent contents

import slowlette
webapi = slowlette.Slowlette()


@webapi.get('/channels')
def get_channels():
    return [ { 'name': 'data_query', 'type': 'tree' } ]


@webapi.get('/data/{channels}')
def get_data(channels:str, length:float=None, to:float=None, resample:float=None, reducer:str=None):
    if 'data_query' not in channels.split(','):
        return None
    
    record = { "data_query": { "x": {
        'tree': {
            'channels': channels,
            'length': length,
            'to': to,
            'resample': resample,
            'reducer': reducer,
        }
    }}}

    return record



#### Example for dynamically adding a slowplot layout (that displays all the time-series channels)

channels = []
async def _setup(slowdash):
    global channels
    channels = await slowdash.request_channels()

    
@webapi.get('/config/contentlist')
def add_slowplot_PlotLayoutOverride():
    return [{
        "type": "slowplot",
        "name": "PlotLayoutOverride",
        "description": "Dynamically generated by UserModule",
        "config_file": "slowplot-PlotLayoutOverride.json"
    }]


@webapi.get('/config/content/slowplot-PlotLayoutOverride.json')
def generate_slowplot_PlotLayoutOverride(request:slowlette.Request):
    request.abort()   # stop propagation, in order not to be handled by SlowDash

    layout = {
        "panels": [{
            "type": "timeaxis",
            "plots": [{ "type": "timeseries", "channel": ch['name'] }]
        } for ch in channels if ch.get('type', 'numeric') == 'numeric' ]
    }

    return layout



if __name__ == '__main__':
    print(get_channels())
    print(get_data('data_query'))

    channels = [ {'name': ch, 'type': 'numeric'} for ch in ['ch0', 'ch1', 'ch2', 'ch3' ] ]
    print(add_slowplot_PlotLayoutOverride())
    print(generate_slowplot_PlotLayoutOverride(slowlette.Request('')))
