services:
  apache:
    build: .
    container_name: apache_proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./ssl:/etc/apache2/ssl
    networks:
      - slownet

networks:
  slownet:
    driver: bridge
