
services:
  apache:
    build: .
    container_name: apache_proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./ssl:/usr/local/apache2/conf/ssl
    extra_hosts:
      - "host.docker.internal:host-gateway"
