
services:
  jupyter:
    image: slowproj/slowpy-notebook
    command:
      - start-notebook.sh
      - --NotebookApp.token=SlowJupyter
    ports:
      - 8888:8888
    volumes:
      - ./notebooks:/home/jovyan


  slowdash:
    image: slowproj/slowdash
    volumes:
      - .:/project
    ports:
      - "18881:18881"
    environment:
      - JUPYTER_URL=http://localhost:8888
      - JUPYTER_TOKEN=SlowJupyter
      - JUPYTER_INTERNAL_URL=http://jupyter:8888
      - SLOWDASH_INTERNAL_URL=http://slowdash:18881
      
