
services:
  apache:
    build: ./apache2
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - slowdash


  slowdash:
    image: slowproj/slowdash
    expose:
      - "18881"
    volumes:
      - .:/project
