
import slowlette
webapi = slowlette.Slowlette()



#### Example for dynamically adding a channel for time-range-dependent contents

@webapi.get('/api/channels')
def get_channels():
    return [ { 'name': 'data_query', 'type': 'tree' } ]


@webapi.get('/api/data/{channels}')
def get_data(channels:str, length:float=None, to:float=None, resample:float=None, reducer:str=None):
    if 'data_query' not in channels.split(','):
        return None
    
    record = { "data_query": { "x": {
        'tree': {
            'channels': channels,
            'length': length,
            'to': to,
            'resample': resample,
            'reducer': reducer,
        }
    }}}

    return record



#### Example for dynamically adding a slowplot layout (that displays all the time-series channels)

channels = []
async def _setup(slowdash):
    global channels
    channels = await slowdash.request_channels()

    
@webapi.get('/api/config/contentlist')
def add_slowplot_PlotLayoutOverride():
    # this entry will be "injected" into the list, through Slowlette's response aggregation
    entries = [{
        "type": "slowplot",
        "name": "PlotLayoutOverride",
        "config_file": "slowplot-PlotLayoutOverride.json",
        "description": "Dynamically generated by UserModule"
    }]

    return entries


@webapi.get('/api/config/content/slowplot-PlotLayoutOverride.json')
def generate_slowplot_PlotLayoutOverride(request:slowlette.Request):
    request.abort()   # stop propagation, in order not to be handled by SlowDash (disable aggregation)

    layout = {
        "panels": [{
            "type": "timeaxis",
            "plots": [{ "type": "timeseries", "channel": ch['name'] }]
        } for ch in channels if ch.get('type', 'numeric') == 'numeric' ]
    }

    return layout



#### For development: running Web Server standalone (without SlowDash)

if __name__ == '__main__':
    channels = [ {'name': ch, 'type': 'numeric'} for ch in ['ch0', 'ch1', 'ch2', 'ch3' ] ]

    webapi.run()
    # to test:
    # - curl http://localhost:8000/channels
    # - curl http://localhost:8000/data/data_query
    # - curl http://localhost:8000/config/contentlist
    # - curl http://localhost:8000/config/content/slowplot-PlotLayoutOverride.json
